<?php

if( function_exists('acf_add_local_field_group') ):
//
//	acf_add_local_field_group(array (
//		'key' => 'group_5aae95067d406',
//		'title' => 'Header - Theme Options',
//		'fields' => array (
//			array (
//				'key' => 'field_5aae950eb7009',
//				'label' => 'Main Logo',
//				'name' => 'main_logo',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array (
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'full',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//			array (
//				'key' => 'field_5aae96d1355c5',
//				'label' => 'Width',
//				'name' => 'width',
//				'type' => 'number',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array (
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => 'px',
//				'min' => '',
//				'max' => '',
//				'step' => '',
//				'readonly' => 0,
//				'disabled' => 0,
//			),
//			array (
//				'key' => 'field_5aae96e7355c6',
//				'label' => 'Height',
//				'name' => 'height',
//				'type' => 'number',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array (
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'default_value' => '',
//				'placeholder' => '',
//				'prepend' => '',
//				'append' => 'px',
//				'min' => '',
//				'max' => '',
//				'step' => '',
//				'readonly' => 0,
//				'disabled' => 0,
//			),
//			array (
//				'key' => 'field_5aae9532b700a',
//				'label' => 'Mobile Logo',
//				'name' => 'mobile_logo',
//				'type' => 'image',
//				'instructions' => '',
//				'required' => 0,
//				'conditional_logic' => 0,
//				'wrapper' => array (
//					'width' => '',
//					'class' => '',
//					'id' => '',
//				),
//				'return_format' => 'url',
//				'preview_size' => 'thumbnail',
//				'library' => 'all',
//				'min_width' => '',
//				'min_height' => '',
//				'min_size' => '',
//				'max_width' => '',
//				'max_height' => '',
//				'max_size' => '',
//				'mime_types' => '',
//			),
//		),
//		'location' => array (
//			array (
//				array (
//					'param' => 'options_page',
//					'operator' => '==',
//					'value' => 'acf-options-header',
//				),
//			),
//		),
//		'menu_order' => 0,
//		'position' => 'normal',
//		'style' => 'default',
//		'label_placement' => 'top',
//		'instruction_placement' => 'label',
//		'hide_on_screen' => '',
//		'active' => 1,
//		'description' => '',
//	));

endif;